Resolve "worker.periodic.tasks.flush_lazybytes.flush_lazybytes: cannot access local variable 'file_id'"
# 📌 Summary

Fixes the exception:

```
Traceback (most recent call last):
  File "/code/.venv/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/code/common/common/celery_app.py", line 88, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/worker/worker/periodic/tasks/flush_lazybytes.py", line 20, in flush_lazybytes
    get_lazybytes_service().flush()
  File "/code/common/common/services/lazybytes_service.py", line 235, in flush
    self._bucket.delete(file_id)
                        ^^^^^^^
UnboundLocalError: cannot access local variable 'file_id' where it is not associated with a value
```

## 🔗 Issue Reference

<!--
If this MR was created to resolve a specific issue, reference it here.
This ensures the issue is automatically closed when the MR is merged.
Example:
Closes #123
-->

Closes #131

See merge request swiss-armed-forces/cyber-command/cea/loom!141